// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30ooF5Yxw6jWjWOhDyVSWvStlYUCKPFg',
    appId: '1:658492732118:web:76eccf29915957c04acf77',
    messagingSenderId: '658492732118',
    projectId: 'salmon-roe-a38eb',
    authDomain: 'salmon-roe-a38eb.firebaseapp.com',
    storageBucket: 'salmon-roe-a38eb.firebasestorage.app',
    measurementId: 'G-NZKPJ961T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3J5CxvpNB2Jc9cjMGfzkBxx5H8sHpHE8',
    appId: '1:658492732118:android:c921a9db3ddc0e784acf77',
    messagingSenderId: '658492732118',
    projectId: 'salmon-roe-a38eb',
    storageBucket: 'salmon-roe-a38eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO0eObR-YaaNdKdRrDT16fcETxVQA8k4g',
    appId: '1:658492732118:ios:9c73cd9b440755734acf77',
    messagingSenderId: '658492732118',
    projectId: 'salmon-roe-a38eb',
    storageBucket: 'salmon-roe-a38eb.firebasestorage.app',
    iosBundleId: 'br.com.roeshushitcc.flutterCreateTcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD30ooF5Yxw6jWjWOhDyVSWvStlYUCKPFg',
    appId: '1:658492732118:web:83e34dce7c21b4674acf77',
    messagingSenderId: '658492732118',
    projectId: 'salmon-roe-a38eb',
    authDomain: 'salmon-roe-a38eb.firebaseapp.com',
    storageBucket: 'salmon-roe-a38eb.firebasestorage.app',
    measurementId: 'G-CDHBBCY3DM',
  );
}
